name: minvest_forex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Ecosystem
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.10
  cloud_functions: ^5.2.1

  # Authentication
  google_sign_in: 6.3.0
  flutter_facebook_auth: 7.0.1
  sign_in_with_apple:

  # State Management & Core Utilities
  flutter_bloc:
  equatable:
  provider:
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  google_fonts:

  # Other packages
  app_tracking_transparency:
  cupertino_icons:
  url_launcher:
  image_picker:
  webview_flutter: ^4.13.1
  in_app_purchase:
  flutter_local_notifications:
  device_info_plus:
  crypto:
  uuid:
  in_app_purchase_storekit:
  visibility_detector:
  flutter_quill:
  font_awesome_flutter: ^10.9.1
  flutter_svg: ^2.2.3
  web_socket_channel: ^3.0.3
  flutter_native_splash: ^2.4.7
  share_plus: ^12.0.1
  app_settings: ^7.0.0
  external_app_launcher: ^4.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_signalgpt.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo_signalgpt.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/mockups/splash_screen.png"
  android: true
  ios: true
  web: false
  fullscreen: true
  android_gravity: center
  android_12:
    image: "assets/images/logo_signalgpt.png"
    color: "#000000"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mockups/
    - assets/icons/
    - assets/landing_page/
  fonts:
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
